#!/usr/bin/bash


INIT_BROKERS="{{ brokers }}"
WORK_BROKERS=$INIT_BROKERS
ITERATE_BROKERS="$INIT_BROKERS all"
WORK_DIR="{{parts.buildout.directory}}/var/reports"
BIN_DIR="{{parts.buildout.directory}}/bin"
START="$(date -d'-1 month' +'%Y-%m')-01"
END="$(date  +'%Y-%m')-01"




parse_date () {

    IFS='-' read -r year month day< <(echo "$1")
    if [ -z "$year" ] || [ -z "$month" ] || [ -z "$day" ]; then
        year=$(date +'%Y')
        if [ -z "$month" ] && [ -z "$day" ]; then
            month="$1"
            day="01"
        fi
        if ! [ -z "$month" ] && [ -z "$day" ]; then
            IFS='-' read -r month day< <(echo "$1")
        fi
    fi

    date -d"$year-$month-$day" +'%Y-%m-%d'
}


if [[ -n $BROKER_FILES ]]; then
    broker_files_re="\(invoices\|bids\)"
else
    broker_files_re="\(invoices\|bids\|refunds\|tenders\)"
fi



if [ !  -z "$1" ]; then
    if [[ $INIT_BROKERS =~ .*"$1".* ]]; then
        WORK_BROKERS=$@
        ITERATE_BROKERS=$@
    elif [[ "all" == "$1" ]]; then
        WORK_BROKERS=$INIT_BROKERS
        ITERATE_BROKERS="all"
    else
        START="$(parse_date "$1")"
        if [ ! -z "$2" ]; then
            END="$(parse_date "$2")"
        fi

    fi
fi


echo "Generating reports form $START to $END"
echo

for broker in $WORK_BROKERS;do


    FILE_PATTERN="${WORK_DIR}/${broker}@$START--$END"
    for cmd in bids tenders invoices refunds; do
        echo "Generating ${cmd} for ${broker}"
        "${BIN_DIR}/${cmd}" -b "$broker" -p "$START" "$END"
    done

    passwd=$(pass "{{ zip_path }}/$broker")
    echo "Creating zip file with bids and invoices for ${broker}"
    find "$WORK_DIR"  -maxdepth 1 -regex "$FILE_PATTERN-$broker_files_re.csv" | xargs -L 4 "${BIN_DIR}/zip" -p "$passwd"  -f 
    echo
done
echo

echo "Creating zip archive with invoices"


passwd=$(pass "{{zip_path}}/all")
cat $WORK_DIR/*@$START--$END-bids.csv | head -n 1 > "$WORK_DIR/all@$START--$END-bids.csv"
cat $WORK_DIR/*@$START--$END-bids.csv | sort -u | head -n -1  >> "$WORK_DIR/all@$START--$END-bids.csv"
find $WORK_DIR/ -regex ".*@$START--$END-\(invoices\|bids\).csv" | grep 'invoices\|all' | xargs "${BIN_DIR}/zip" -p $passwd -z  "all@$START--$END-bids.zip" -f


rm "$WORK_DIR/all@$START--$END-bids.csv"
echo



echo "Creating zip archive with refunds"
find "$WORK_DIR" -maxdepth 1 -regex ".*@$START--$END-\(tenders\|refunds\).csv" | xargs "${BIN_DIR}/zip" -z "all@$START--$END-tenders.zip" -f
echo
echo "Sending to s3"
for broker in $ITERATE_BROKERS; do
    find "$WORK_DIR" -maxdepth 1 -name "$broker@$START--$END*.zip" -exec  $BIN_DIR/send -n -f "{}"  \;
done

find "$WORK_DIR" -maxdepth 1 -name "*@$START--$END*.csv" -exec rm "{}" \;
